// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/cart_id_model.dart';
import 'data/models/product_model.dart';
import 'data/models/user_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 5587301428208193857),
      name: 'ProductModel',
      lastPropertyId: const obx_int.IdUid(27, 6637250826489806182),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2742163525108094734),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4454704368887628467),
            name: 'productId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4132702461060122426),
            name: 'productName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4490049318464460355),
            name: 'customTitle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3203312155954036746),
            name: 'friendlyName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3595218138368846694),
            name: 'productDesc',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6118460128575844155),
            name: 'imagePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8801517273218465903),
            name: 'price',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 1167469172078119683),
            name: 'isActive',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 1887313357648289836),
            name: 'isFeatured',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 2693077731407684803),
            name: 'isOffer',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 1790020357452620715),
            name: 'isOfferActive',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 4825260703865077167),
            name: 'hasDiscount',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 3080154666403313993),
            name: 'productMrp',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 1594003145244501995),
            name: 'discountAmount',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 5951202863560578031),
            name: 'mainCategory',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 4199879666124072390),
            name: 'productSize',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 2297394308073886728),
            name: 'brandId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 3368424008833610113),
            name: 'qtyInStock',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 872182133195202800),
            name: 'sortOrder',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(21, 4169805604342977520),
            name: 'activeStatus',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(22, 1013205454386971764),
            name: 'categoryId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(23, 2850328560324385045),
            name: 'productSubCatId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(24, 1674220334145349676),
            name: 'ratingCount',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(25, 2079020913239925873),
            name: 'discountedPrice',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(26, 526985907074822053),
            name: 'offerDiscountPercent',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(27, 6637250826489806182),
            name: 'userName',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 954951442911416934),
      name: 'CartIdModel',
      lastPropertyId: const obx_int.IdUid(4, 1321773969203979692),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8507346071276558164),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 103283982620772581),
            name: 'cartId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1127152025800285983),
            name: 'userId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1321773969203979692),
            name: 'cartCount',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 3025411276219141613),
      name: 'UserModel',
      lastPropertyId: const obx_int.IdUid(21, 3045940047531275522),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5991948224025947981),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2188977671814324798),
            name: 'firstName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5048600904247167809),
            name: 'lastName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3499302716622572780),
            name: 'userName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8260107553426690568),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 7573414318103972908),
            name: 'password',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 9088138492277885102),
            name: 'userType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 702283323956234208),
            name: 'registerDate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 200217844351891946),
            name: 'activationId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 8807904402101765592),
            name: 'billingTelephone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 1834462795263999862),
            name: 'billingAddress',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 1446139140529916916),
            name: 'billingCity',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 2349653718955294507),
            name: 'billingState',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 6412780191909285276),
            name: 'billingZip',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 5821040065958628782),
            name: 'billingCountry',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 1150066784521224725),
            name: 'shippingAddress',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 4640173600022355755),
            name: 'shippingCity',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 1203164751059596471),
            name: 'shippingState',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 5183542610606719099),
            name: 'shippingZip',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 4913756234105241242),
            name: 'shippingCountry',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(21, 3045940047531275522),
            name: 'shippingTelephone',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(6, 2179272222040295921),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [
        3232157932175725669,
        4033061857859664763,
        2179272222040295921
      ],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        1344926381579306182,
        44995991299096206,
        1940358856626043052,
        6567640067826126197,
        7394150973244831675,
        6895024330860823696,
        8985560519214499920,
        2511599843845498497,
        9110208283130532383,
        5184838288084380541,
        6289745094537169964,
        5369123860223398344,
        6235491224946919181,
        167605031177928261,
        8847444880680593906,
        8700607622626514230,
        6927507070076941253,
        2216418572481176674,
        6697349037285648724,
        6998610290188264893,
        6586449370038572999,
        4134157567191231044,
        6919011816797914875,
        3941408322597465265,
        5787484430934753546,
        7165699181777950054,
        617670364561622771,
        7239592952447478113,
        3426842178951825941,
        778708125292725061,
        6797360864483878289,
        442496238164420883,
        2592138613916837027,
        8238634324144752390,
        7798781125839347488,
        3555289055452794595,
        123037477911849095,
        5906925602086587763,
        2840140404992383646,
        2268157102697146308,
        8418941135634229446,
        7169369066728631791,
        6386818621058757837,
        6165417231511221705,
        7238710646666504442,
        1355648237521161120,
        5206514469465824966,
        5293949441574478270
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ProductModel: obx_int.EntityDefinition<ProductModel>(
        model: _entities[0],
        toOneRelations: (ProductModel object) => [],
        toManyRelations: (ProductModel object) => {},
        getId: (ProductModel object) => object.id,
        setId: (ProductModel object, int id) {
          object.id = id;
        },
        objectToFB: (ProductModel object, fb.Builder fbb) {
          final productIdOffset = object.productId == null
              ? null
              : fbb.writeString(object.productId!);
          final productNameOffset = object.productName == null
              ? null
              : fbb.writeString(object.productName!);
          final customTitleOffset = object.customTitle == null
              ? null
              : fbb.writeString(object.customTitle!);
          final friendlyNameOffset = object.friendlyName == null
              ? null
              : fbb.writeString(object.friendlyName!);
          final productDescOffset = object.productDesc == null
              ? null
              : fbb.writeString(object.productDesc!);
          final imagePathOffset = object.imagePath == null
              ? null
              : fbb.writeString(object.imagePath!);
          final priceOffset =
              object.price == null ? null : fbb.writeString(object.price!);
          final isActiveOffset = object.isActive == null
              ? null
              : fbb.writeString(object.isActive!);
          final isFeaturedOffset = object.isFeatured == null
              ? null
              : fbb.writeString(object.isFeatured!);
          final isOfferOffset =
              object.isOffer == null ? null : fbb.writeString(object.isOffer!);
          final isOfferActiveOffset = object.isOfferActive == null
              ? null
              : fbb.writeString(object.isOfferActive!);
          final hasDiscountOffset = object.hasDiscount == null
              ? null
              : fbb.writeString(object.hasDiscount!);
          final productMrpOffset = object.productMrp == null
              ? null
              : fbb.writeString(object.productMrp!);
          final discountAmountOffset = object.discountAmount == null
              ? null
              : fbb.writeString(object.discountAmount!);
          final mainCategoryOffset = object.mainCategory == null
              ? null
              : fbb.writeString(object.mainCategory!);
          final productSizeOffset = object.productSize == null
              ? null
              : fbb.writeString(object.productSize!);
          final brandIdOffset =
              object.brandId == null ? null : fbb.writeString(object.brandId!);
          final qtyInStockOffset = object.qtyInStock == null
              ? null
              : fbb.writeString(object.qtyInStock!);
          final sortOrderOffset = object.sortOrder == null
              ? null
              : fbb.writeString(object.sortOrder!);
          final activeStatusOffset = object.activeStatus == null
              ? null
              : fbb.writeString(object.activeStatus!);
          final categoryIdOffset = object.categoryId == null
              ? null
              : fbb.writeString(object.categoryId!);
          final productSubCatIdOffset = object.productSubCatId == null
              ? null
              : fbb.writeString(object.productSubCatId!);
          final ratingCountOffset = object.ratingCount == null
              ? null
              : fbb.writeString(object.ratingCount!);
          final discountedPriceOffset = object.discountedPrice == null
              ? null
              : fbb.writeString(object.discountedPrice!);
          final offerDiscountPercentOffset = object.offerDiscountPercent == null
              ? null
              : fbb.writeString(object.offerDiscountPercent!);
          final userNameOffset = object.userName == null
              ? null
              : fbb.writeString(object.userName!);
          fbb.startTable(28);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, productIdOffset);
          fbb.addOffset(2, productNameOffset);
          fbb.addOffset(3, customTitleOffset);
          fbb.addOffset(4, friendlyNameOffset);
          fbb.addOffset(5, productDescOffset);
          fbb.addOffset(6, imagePathOffset);
          fbb.addOffset(7, priceOffset);
          fbb.addOffset(8, isActiveOffset);
          fbb.addOffset(9, isFeaturedOffset);
          fbb.addOffset(10, isOfferOffset);
          fbb.addOffset(11, isOfferActiveOffset);
          fbb.addOffset(12, hasDiscountOffset);
          fbb.addOffset(13, productMrpOffset);
          fbb.addOffset(14, discountAmountOffset);
          fbb.addOffset(15, mainCategoryOffset);
          fbb.addOffset(16, productSizeOffset);
          fbb.addOffset(17, brandIdOffset);
          fbb.addOffset(18, qtyInStockOffset);
          fbb.addOffset(19, sortOrderOffset);
          fbb.addOffset(20, activeStatusOffset);
          fbb.addOffset(21, categoryIdOffset);
          fbb.addOffset(22, productSubCatIdOffset);
          fbb.addOffset(23, ratingCountOffset);
          fbb.addOffset(24, discountedPriceOffset);
          fbb.addOffset(25, offerDiscountPercentOffset);
          fbb.addOffset(26, userNameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final activeStatusParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 44);
          final brandIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 38);
          final categoryIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 46);
          final customTitleParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final discountAmountParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 32);
          final friendlyNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final hasDiscountParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 28);
          final imagePathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final isActiveParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final isFeaturedParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 22);
          final isOfferParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 24);
          final isOfferActiveParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 26);
          final mainCategoryParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 34);
          final priceParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final productDescParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14);
          final productIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final productMrpParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 30);
          final productNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8);
          final productSizeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 36);
          final productSubCatIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 48);
          final qtyInStockParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 40);
          final ratingCountParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 50);
          final sortOrderParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 42);
          final discountedPriceParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 52);
          final offerDiscountPercentParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 54);
          final userNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 56);
          final object = ProductModel(
              activeStatus: activeStatusParam,
              brandId: brandIdParam,
              categoryId: categoryIdParam,
              customTitle: customTitleParam,
              discountAmount: discountAmountParam,
              friendlyName: friendlyNameParam,
              hasDiscount: hasDiscountParam,
              imagePath: imagePathParam,
              isActive: isActiveParam,
              isFeatured: isFeaturedParam,
              isOffer: isOfferParam,
              isOfferActive: isOfferActiveParam,
              mainCategory: mainCategoryParam,
              price: priceParam,
              productDesc: productDescParam,
              productId: productIdParam,
              productMrp: productMrpParam,
              productName: productNameParam,
              productSize: productSizeParam,
              productSubCatId: productSubCatIdParam,
              qtyInStock: qtyInStockParam,
              ratingCount: ratingCountParam,
              sortOrder: sortOrderParam,
              discountedPrice: discountedPriceParam,
              offerDiscountPercent: offerDiscountPercentParam,
              userName: userNameParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    CartIdModel: obx_int.EntityDefinition<CartIdModel>(
        model: _entities[1],
        toOneRelations: (CartIdModel object) => [],
        toManyRelations: (CartIdModel object) => {},
        getId: (CartIdModel object) => object.id,
        setId: (CartIdModel object, int id) {
          object.id = id;
        },
        objectToFB: (CartIdModel object, fb.Builder fbb) {
          final cartIdOffset =
              object.cartId == null ? null : fbb.writeString(object.cartId!);
          final userIdOffset =
              object.userId == null ? null : fbb.writeString(object.userId!);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, cartIdOffset);
          fbb.addOffset(2, userIdOffset);
          fbb.addInt64(3, object.cartCount);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final cartIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final userIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final object = CartIdModel(cartIdParam, userIdParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..cartCount = const fb.Int64Reader()
                .vTableGetNullable(buffer, rootOffset, 10);

          return object;
        }),
    UserModel: obx_int.EntityDefinition<UserModel>(
        model: _entities[2],
        toOneRelations: (UserModel object) => [],
        toManyRelations: (UserModel object) => {},
        getId: (UserModel object) => object.id,
        setId: (UserModel object, int id) {
          object.id = id;
        },
        objectToFB: (UserModel object, fb.Builder fbb) {
          final firstNameOffset = object.firstName == null
              ? null
              : fbb.writeString(object.firstName!);
          final lastNameOffset = object.lastName == null
              ? null
              : fbb.writeString(object.lastName!);
          final userNameOffset = object.userName == null
              ? null
              : fbb.writeString(object.userName!);
          final emailOffset =
              object.email == null ? null : fbb.writeString(object.email!);
          final passwordOffset = object.password == null
              ? null
              : fbb.writeString(object.password!);
          final userTypeOffset = object.userType == null
              ? null
              : fbb.writeString(object.userType!);
          final registerDateOffset = object.registerDate == null
              ? null
              : fbb.writeString(object.registerDate!);
          final activationIdOffset = object.activationId == null
              ? null
              : fbb.writeString(object.activationId!);
          final billingTelephoneOffset = object.billingTelephone == null
              ? null
              : fbb.writeString(object.billingTelephone!);
          final billingAddressOffset = object.billingAddress == null
              ? null
              : fbb.writeString(object.billingAddress!);
          final billingCityOffset = object.billingCity == null
              ? null
              : fbb.writeString(object.billingCity!);
          final billingStateOffset = object.billingState == null
              ? null
              : fbb.writeString(object.billingState!);
          final billingZipOffset = object.billingZip == null
              ? null
              : fbb.writeString(object.billingZip!);
          final billingCountryOffset = object.billingCountry == null
              ? null
              : fbb.writeString(object.billingCountry!);
          final shippingAddressOffset = object.shippingAddress == null
              ? null
              : fbb.writeString(object.shippingAddress!);
          final shippingCityOffset = object.shippingCity == null
              ? null
              : fbb.writeString(object.shippingCity!);
          final shippingStateOffset = object.shippingState == null
              ? null
              : fbb.writeString(object.shippingState!);
          final shippingZipOffset = object.shippingZip == null
              ? null
              : fbb.writeString(object.shippingZip!);
          final shippingCountryOffset = object.shippingCountry == null
              ? null
              : fbb.writeString(object.shippingCountry!);
          final shippingTelephoneOffset = object.shippingTelephone == null
              ? null
              : fbb.writeString(object.shippingTelephone!);
          fbb.startTable(22);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, firstNameOffset);
          fbb.addOffset(2, lastNameOffset);
          fbb.addOffset(3, userNameOffset);
          fbb.addOffset(4, emailOffset);
          fbb.addOffset(5, passwordOffset);
          fbb.addOffset(6, userTypeOffset);
          fbb.addOffset(7, registerDateOffset);
          fbb.addOffset(8, activationIdOffset);
          fbb.addOffset(9, billingTelephoneOffset);
          fbb.addOffset(10, billingAddressOffset);
          fbb.addOffset(11, billingCityOffset);
          fbb.addOffset(12, billingStateOffset);
          fbb.addOffset(13, billingZipOffset);
          fbb.addOffset(14, billingCountryOffset);
          fbb.addOffset(15, shippingAddressOffset);
          fbb.addOffset(16, shippingCityOffset);
          fbb.addOffset(17, shippingStateOffset);
          fbb.addOffset(18, shippingZipOffset);
          fbb.addOffset(19, shippingCountryOffset);
          fbb.addOffset(20, shippingTelephoneOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final activationIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20);
          final billingAddressParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 24);
          final billingCityParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 26);
          final billingCountryParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 32);
          final billingStateParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 28);
          final billingTelephoneParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 22);
          final billingZipParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 30);
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final firstNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final lastNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final passwordParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final registerDateParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18);
          final shippingAddressParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 34);
          final shippingCityParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 36);
          final shippingCountryParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 42);
          final shippingStateParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 38);
          final shippingZipParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 40);
          final shippingTelephoneParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 44);
          final userNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final userTypeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final object = UserModel(
              activationId: activationIdParam,
              billingAddress: billingAddressParam,
              billingCity: billingCityParam,
              billingCountry: billingCountryParam,
              billingState: billingStateParam,
              billingTelephone: billingTelephoneParam,
              billingZip: billingZipParam,
              email: emailParam,
              firstName: firstNameParam,
              lastName: lastNameParam,
              password: passwordParam,
              registerDate: registerDateParam,
              shippingAddress: shippingAddressParam,
              shippingCity: shippingCityParam,
              shippingCountry: shippingCountryParam,
              shippingState: shippingStateParam,
              shippingZip: shippingZipParam,
              shippingTelephone: shippingTelephoneParam,
              userName: userNameParam,
              userType: userTypeParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ProductModel] entity fields to define ObjectBox queries.
class ProductModel_ {
  /// See [ProductModel.id].
  static final id =
      obx.QueryIntegerProperty<ProductModel>(_entities[0].properties[0]);

  /// See [ProductModel.productId].
  static final productId =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[1]);

  /// See [ProductModel.productName].
  static final productName =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[2]);

  /// See [ProductModel.customTitle].
  static final customTitle =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[3]);

  /// See [ProductModel.friendlyName].
  static final friendlyName =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[4]);

  /// See [ProductModel.productDesc].
  static final productDesc =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[5]);

  /// See [ProductModel.imagePath].
  static final imagePath =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[6]);

  /// See [ProductModel.price].
  static final price =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[7]);

  /// See [ProductModel.isActive].
  static final isActive =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[8]);

  /// See [ProductModel.isFeatured].
  static final isFeatured =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[9]);

  /// See [ProductModel.isOffer].
  static final isOffer =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[10]);

  /// See [ProductModel.isOfferActive].
  static final isOfferActive =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[11]);

  /// See [ProductModel.hasDiscount].
  static final hasDiscount =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[12]);

  /// See [ProductModel.productMrp].
  static final productMrp =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[13]);

  /// See [ProductModel.discountAmount].
  static final discountAmount =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[14]);

  /// See [ProductModel.mainCategory].
  static final mainCategory =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[15]);

  /// See [ProductModel.productSize].
  static final productSize =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[16]);

  /// See [ProductModel.brandId].
  static final brandId =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[17]);

  /// See [ProductModel.qtyInStock].
  static final qtyInStock =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[18]);

  /// See [ProductModel.sortOrder].
  static final sortOrder =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[19]);

  /// See [ProductModel.activeStatus].
  static final activeStatus =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[20]);

  /// See [ProductModel.categoryId].
  static final categoryId =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[21]);

  /// See [ProductModel.productSubCatId].
  static final productSubCatId =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[22]);

  /// See [ProductModel.ratingCount].
  static final ratingCount =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[23]);

  /// See [ProductModel.discountedPrice].
  static final discountedPrice =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[24]);

  /// See [ProductModel.offerDiscountPercent].
  static final offerDiscountPercent =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[25]);

  /// See [ProductModel.userName].
  static final userName =
      obx.QueryStringProperty<ProductModel>(_entities[0].properties[26]);
}

/// [CartIdModel] entity fields to define ObjectBox queries.
class CartIdModel_ {
  /// See [CartIdModel.id].
  static final id =
      obx.QueryIntegerProperty<CartIdModel>(_entities[1].properties[0]);

  /// See [CartIdModel.cartId].
  static final cartId =
      obx.QueryStringProperty<CartIdModel>(_entities[1].properties[1]);

  /// See [CartIdModel.userId].
  static final userId =
      obx.QueryStringProperty<CartIdModel>(_entities[1].properties[2]);

  /// See [CartIdModel.cartCount].
  static final cartCount =
      obx.QueryIntegerProperty<CartIdModel>(_entities[1].properties[3]);
}

/// [UserModel] entity fields to define ObjectBox queries.
class UserModel_ {
  /// See [UserModel.id].
  static final id =
      obx.QueryIntegerProperty<UserModel>(_entities[2].properties[0]);

  /// See [UserModel.firstName].
  static final firstName =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[1]);

  /// See [UserModel.lastName].
  static final lastName =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[2]);

  /// See [UserModel.userName].
  static final userName =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[3]);

  /// See [UserModel.email].
  static final email =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[4]);

  /// See [UserModel.password].
  static final password =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[5]);

  /// See [UserModel.userType].
  static final userType =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[6]);

  /// See [UserModel.registerDate].
  static final registerDate =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[7]);

  /// See [UserModel.activationId].
  static final activationId =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[8]);

  /// See [UserModel.billingTelephone].
  static final billingTelephone =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[9]);

  /// See [UserModel.billingAddress].
  static final billingAddress =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[10]);

  /// See [UserModel.billingCity].
  static final billingCity =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[11]);

  /// See [UserModel.billingState].
  static final billingState =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[12]);

  /// See [UserModel.billingZip].
  static final billingZip =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[13]);

  /// See [UserModel.billingCountry].
  static final billingCountry =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[14]);

  /// See [UserModel.shippingAddress].
  static final shippingAddress =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[15]);

  /// See [UserModel.shippingCity].
  static final shippingCity =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[16]);

  /// See [UserModel.shippingState].
  static final shippingState =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[17]);

  /// See [UserModel.shippingZip].
  static final shippingZip =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[18]);

  /// See [UserModel.shippingCountry].
  static final shippingCountry =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[19]);

  /// See [UserModel.shippingTelephone].
  static final shippingTelephone =
      obx.QueryStringProperty<UserModel>(_entities[2].properties[20]);
}
